using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class EquipmentNamer {
    private readonly static Dictionary<string, NameModifier> modifiers = new Dictionary<string, NameModifier>() {
        { "strength_dexterity", new NameModifier() { isSuffix=false, text="Deft" } },
        { "dexterity_strength", new NameModifier() { isSuffix=false, text="Deft" } },
        { "strength_constitution", new NameModifier() { text="Moxie" } },
        { "constitution_strength", new NameModifier() { text="Moxie" } },
        { "strength_intelligence", new NameModifier() { text="Apprehension" } },
        { "intelligence_strength", new NameModifier() { text="Apprehension" } },
        { "strength_wisdom", new NameModifier() { isSuffix=false, text="Judicious" } },
        { "wisdom_strength", new NameModifier() { isSuffix=false, text="Judicious" } },
        { "strength_luck", new NameModifier() { text="the Horseshoe" } },
        { "luck_strength", new NameModifier() { text="the Horseshoe" } },
        { "strength_hpRating", new NameModifier() { isSuffix=false, text="Brawny" } },
        { "hpRating_strength", new NameModifier() { isSuffix=false, text="Brawny" } },
        { "strength_hpRegenRating", new NameModifier() { isSuffix=false, text="Flexible" } },
        { "hpRegenRating_strength", new NameModifier() { isSuffix=false, text="Flexible" } },
        { "strength_receivedHealingRating", new NameModifier() { text="Resilience" } },
        { "receivedHealingRating_strength", new NameModifier() { text="Resilience" } },
        { "strength_armorMultiplierRating", new NameModifier() { isSuffix=false, text="Steely" } },
        { "armorMultiplierRating_strength", new NameModifier() { isSuffix=false, text="Steely" } },
        { "strength_physicalResistRating", new NameModifier() { isSuffix=false, text="Rugged" } },
        { "physicalResistRating_strength", new NameModifier() { isSuffix=false, text="Rugged" } },
        { "strength_mentalResistRating", new NameModifier() { isSuffix=false, text="Tenacious" } },
        { "mentalResistRating_strength", new NameModifier() { isSuffix=false, text="Tenacious" } },
        { "strength_mpRating", new NameModifier() { isSuffix=false, text="Occult" } },
        { "mpRating_strength", new NameModifier() { isSuffix=false, text="Occult" } },
        { "strength_healingMultiplierRating", new NameModifier() { isSuffix=false, text="Sanative" } },
        { "healingMultiplierRating_strength", new NameModifier() { isSuffix=false, text="Sanative" } },
        { "strength_moveSpeedRating", new NameModifier() { isSuffix=false, text="Energetic" } },
        { "moveSpeedRating_strength", new NameModifier() { isSuffix=false, text="Energetic" } },
        { "strength_cooldownReductionRating", new NameModifier() { text="Providence" } },
        { "cooldownReductionRating_strength", new NameModifier() { text="Providence" } },
        { "strength_mpRegenRating", new NameModifier() { text="the Enigma" } },
        { "mpRegenRating_strength", new NameModifier() { text="the Enigma" } },
        { "strength_criticalHitChanceRating", new NameModifier() { isSuffix=false, text="Auspicious" } },
        { "criticalHitChanceRating_strength", new NameModifier() { isSuffix=false, text="Auspicious" } },
        { "strength_criticalDamageRating", new NameModifier() { text="the Butcher" } },
        { "criticalDamageRating_strength", new NameModifier() { text="the Butcher" } },
        { "strength_statusEffectDurationRating", new NameModifier() { isSuffix=false, text="Talisman" } },
        { "statusEffectDurationRating_strength", new NameModifier() { isSuffix=false, text="Talisman" } },
        { "strength_itemFindRating", new NameModifier() { text="the Eumoirous" } },
        { "itemFindRating_strength", new NameModifier() { text="the Eumoirous" } },
        { "strength_fireResistRating", new NameModifier() { text="the Firebrand" } },
        { "fireResistRating_strength", new NameModifier() { text="the Firebrand" } },
        { "strength_iceResistRating", new NameModifier() { text="the Icebrand" } },
        { "iceResistRating_strength", new NameModifier() { text="the Icebrand" } },
        { "strength_acidResistRating", new NameModifier() { isSuffix=false, text="Solvent" } },
        { "acidResistRating_strength", new NameModifier() { isSuffix=false, text="Solvent" } },
        { "strength_lightResistRating", new NameModifier() { isSuffix=false, text="Dazzling" } },
        { "lightResistRating_strength", new NameModifier() { isSuffix=false, text="Dazzling" } },
        { "strength_darkResistRating", new NameModifier() { isSuffix=false, text="Shadowflex" } },
        { "darkResistRating_strength", new NameModifier() { isSuffix=false, text="Shadowflex" } },
        { "strength_piercingResistRating", new NameModifier() { isSuffix=false, text="Poignant" } },
        { "piercingResistRating_strength", new NameModifier() { isSuffix=false, text="Poignant" } },
        { "strength_slashingResistRating", new NameModifier() { isSuffix=false, text="Sharp" } },
        { "slashingResistRating_strength", new NameModifier() { isSuffix=false, text="Sharp" } },
        { "strength_bashingResistRating", new NameModifier() { isSuffix=false, text="Blunt" } },
        { "bashingResistRating_strength", new NameModifier() { isSuffix=false, text="Blunt" } },

        { "dexterity_constitution", new NameModifier() { isSuffix=false, text="Active" } },
        { "constitution_dexterity", new NameModifier() { isSuffix=false, text="Active" } },
        { "dexterity_intelligence", new NameModifier() { isSuffix=false, text="Adroit" } },
        { "intelligence_dexterity", new NameModifier() { isSuffix=false, text="Adroit" } },
        { "dexterity_wisdom", new NameModifier() { isSuffix=false, text="Sly" } },
        { "wisdom_dexterity", new NameModifier() { isSuffix=false, text="Sly" } },
        { "dexterity_luck", new NameModifier() { isSuffix=false, text="Alert" } },
        { "luck_dexterity", new NameModifier() { isSuffix=false, text="Alert" } },
        { "dexterity_hpRating", new NameModifier() { isSuffix=false, text="Sinewy" } },
        { "hpRating_dexterity", new NameModifier() { isSuffix=false, text="Sinewy" } },
        { "dexterity_hpRegenRating", new NameModifier() { text="the Rebound" } },
        { "hpRegenRating_dexterity", new NameModifier() { text="the Rebound" } },
        { "dexterity_receivedHealingRating", new NameModifier() { text="Alleviation" } },
        { "receivedHealingRating_dexterity", new NameModifier() { text="Alleviation" } },
        { "dexterity_armorMultiplierRating", new NameModifier() { text="Guts" } },
        { "armorMultiplierRating_dexterity", new NameModifier() { text="Guts" } },
        { "dexterity_physicalResistRating", new NameModifier() { isSuffix=false, text="Sinewy" } },
        { "physicalResistRating_dexterity", new NameModifier() { isSuffix=false, text="Sinewy" } },
        { "dexterity_mentalResistRating", new NameModifier() { isSuffix=false, text="Resolute" } },
        { "mentalResistRating_dexterity", new NameModifier() { isSuffix=false, text="Resolute" } },
        { "dexterity_mpRating", new NameModifier() { text="the Sprite" } },
        { "mpRating_dexterity", new NameModifier() { text="the Sprite" } },
        { "dexterity_healingMultiplierRating", new NameModifier() { text="the Burdock" } },
        { "healingMultiplierRating_dexterity", new NameModifier() { text="the Burdock" } },
        { "dexterity_moveSpeedRating", new NameModifier() { isSuffix=false, text="Expeditious" } },
        { "moveSpeedRating_dexterity", new NameModifier() { isSuffix=false, text="Expeditious" } },
        { "dexterity_cooldownReductionRating", new NameModifier() { isSuffix=false, text="Spry" } },
        { "cooldownReductionRating_dexterity", new NameModifier() { isSuffix=false, text="Spry" } },
        { "dexterity_mpRegenRating", new NameModifier() { text="Prestidigitation" } },
        { "mpRegenRating_dexterity", new NameModifier() { text="Prestidigitation" } },
        { "dexterity_criticalHitChanceRating", new NameModifier() { isSuffix=false, text="Brisk" } },
        { "criticalHitChanceRating_dexterity", new NameModifier() { isSuffix=false, text="Brisk" } },
        { "dexterity_criticalDamageRating", new NameModifier() { text="Acuity" } },
        { "criticalDamageRating_dexterity", new NameModifier() { text="Acuity" } },
        { "dexterity_statusEffectDurationRating", new NameModifier() { isSuffix=false, text="Voluble" } },
        { "statusEffectDurationRating_dexterity", new NameModifier() { isSuffix=false, text="Voluble" } },
        { "dexterity_itemFindRating", new NameModifier() { isSuffix=false, text="Clever" } },
        { "itemFindRating_dexterity", new NameModifier() { isSuffix=false, text="Clever" } },
        { "dexterity_fireResistRating", new NameModifier() { text="Combustion" } },
        { "fireResistRating_dexterity", new NameModifier() { text="Combustion" } },
        { "dexterity_iceResistRating", new NameModifier() { text="Sleet" } },
        { "iceResistRating_dexterity", new NameModifier() { text="Sleet" } },
        { "dexterity_acidResistRating", new NameModifier() { text="Astringency" } },
        { "acidResistRating_dexterity", new NameModifier() { text="Astringency" } },
        { "dexterity_lightResistRating", new NameModifier() { isSuffix=false, text="Lithe" } },
        { "lightResistRating_dexterity", new NameModifier() { isSuffix=false, text="Lithe" } },
        { "dexterity_darkResistRating", new NameModifier() { isSuffix=false, text="Bloodwood" } },
        { "darkResistRating_dexterity", new NameModifier() { isSuffix=false, text="Bloodwood" } },
        { "dexterity_piercingResistRating", new NameModifier() { text="the Lance" } },
        { "piercingResistRating_dexterity", new NameModifier() { text="the Lance" } },
        { "dexterity_slashingResistRating", new NameModifier() { text="the Glaive" } },
        { "slashingResistRating_dexterity", new NameModifier() { text="the Glaive" } },
        { "dexterity_bashingResistRating", new NameModifier() { text="the Morningstar" } },
        { "bashingResistRating_dexterity", new NameModifier() { text="the Morningstar" } },
        { "constitution_intelligence", new NameModifier() { isSuffix=false, text="Astute" } },
        { "intelligence_constitution", new NameModifier() { isSuffix=false, text="Astute" } },
        { "constitution_wisdom", new NameModifier() { isSuffix=false, text="Stern" } },
        { "wisdom_constitution", new NameModifier() { isSuffix=false, text="Stern" } },
        { "constitution_luck", new NameModifier() { text="the Rebound" } },
        { "luck_constitution", new NameModifier()  { text="the Rebound" } },
        { "constitution_hpRating", new NameModifier() { isSuffix=false, text="Rugged" } },
        { "hpRating_constitution", new NameModifier() { isSuffix=false, text="Rugged" } },
        { "constitution_hpRegenRating", new NameModifier() { isSuffix=false, text="Enduring" } },
        { "hpRegenRating_constitution", new NameModifier() { isSuffix=false, text="Enduring" } },
        { "constitution_receivedHealingRating", new NameModifier() { text="Inuration" } },
        { "receivedHealingRating_constitution", new NameModifier() { text="Inuration" } },
        { "constitution_armorMultiplierRating", new NameModifier() { isSuffix=false, text="Tough" } },
        { "armorMultiplierRating_constitution", new NameModifier() { isSuffix=false, text="Tough" } },
        { "constitution_physicalResistRating", new NameModifier() { isSuffix=false, text="Pugnacious" } },
        { "physicalResistRating_constitution", new NameModifier() { isSuffix=false, text="Pugnacious" } },
        { "constitution_mentalResistRating", new NameModifier() { text="Bracing" } },
        { "mentalResistRating_constitution", new NameModifier() { text="Bracing" } },
        { "constitution_mpRating", new NameModifier() { isSuffix=false, text="Dwarven" } },
        { "mpRating_constitution", new NameModifier() { isSuffix=false, text="Dwarven" } },
        { "constitution_healingMultiplierRating", new NameModifier() { isSuffix=false, text="Bitterwood" } },
        { "healingMultiplierRating_constitution", new NameModifier() { isSuffix=false, text="Bitterwood" } },
        { "constitution_moveSpeedRating", new NameModifier() { text="the Shark" } },
        { "moveSpeedRating_constitution", new NameModifier() { text="the Shark" } },
        { "constitution_cooldownReductionRating", new NameModifier() { isSuffix=false, text="Springy" } },
        { "cooldownReductionRating_constitution", new NameModifier() { isSuffix=false, text="Springy" } },
        { "constitution_mpRegenRating", new NameModifier() { text="the Gorgon" } },
        { "mpRegenRating_constitution", new NameModifier() { text="the Gorgon" } },
        { "constitution_criticalHitChanceRating", new NameModifier() { text="the Briar" } },
        { "criticalHitChanceRating_constitution", new NameModifier() { text="the Briar" } },
        { "constitution_criticalDamageRating", new NameModifier() { isSuffix=false, text="Hard-Edged" } },
        { "criticalDamageRating_constitution", new NameModifier() { isSuffix=false, text="Hard-Edged" } },
        { "constitution_statusEffectDurationRating", new NameModifier() { isSuffix=false, text="Bacchus" } },
        { "statusEffectDurationRating_constitution", new NameModifier() { isSuffix=false, text="Bacchus" } },
        { "constitution_itemFindRating", new NameModifier() { text="the Hidden Treasure" } },
        { "itemFindRating_constitution", new NameModifier() { text="the Hidden Treasure" } },
        { "constitution_fireResistRating", new NameModifier() { isSuffix=false, text="Ember" } },
        { "fireResistRating_constitution", new NameModifier() { isSuffix=false, text="Ember" } },
        { "constitution_iceResistRating", new NameModifier() { text="Grit" } },
        { "iceResistRating_constitution", new NameModifier() { text="Grit" } },
        { "constitution_acidResistRating", new NameModifier() { isSuffix=false, text="Acerbic" } },
        { "acidResistRating_constitution", new NameModifier() { isSuffix=false, text="Acerbic" } },
        { "constitution_lightResistRating", new NameModifier() { text="the Paladin" } },
        { "lightResistRating_constitution", new NameModifier() { text="the Paladin" } },
        { "constitution_darkResistRating", new NameModifier() { text="the Dark Knight" } },
        { "darkResistRating_constitution", new NameModifier() { text="the Dark Knight" } },
        { "constitution_piercingResistRating", new NameModifier() { text="Nails" } },
        { "piercingResistRating_constitution", new NameModifier() { text="Nails" } },
        { "constitution_slashingResistRating", new NameModifier() { isSuffix=false, text="Hacksaw" } },
        { "slashingResistRating_constitution", new NameModifier() { isSuffix=false, text="Hacksaw" } },
        { "constitution_bashingResistRating", new NameModifier() { isSuffix=false, text="Plated" } },
        { "bashingResistRating_constitution", new NameModifier() { isSuffix=false, text="Plated" } },

        { "intelligence_wisdom", new NameModifier() { isSuffix=false, text="Gnostic" } },
        { "wisdom_intelligence", new NameModifier() { isSuffix=false, text="Gnostic" } },
        { "intelligence_luck", new NameModifier() { isSuffix=false, text="Canny" } },
        { "luck_intelligence", new NameModifier() { isSuffix=false, text="Canny" } },
        { "intelligence_hpRating", new NameModifier() { isSuffix=false, text="Gallant" } },
        { "hpRating_intelligence", new NameModifier() { isSuffix=false, text="Gallant" } },
        { "intelligence_hpRegenRating", new NameModifier() { isSuffix=false, text="Mending" } },
        { "hpRegenRating_intelligence", new NameModifier() { isSuffix=false, text="Mending" } },
        { "intelligence_receivedHealingRating", new NameModifier() { isSuffix=false, text="Spa" } },
        { "receivedHealingRating_intelligence", new NameModifier() { isSuffix=false, text="Spa" } },
        { "intelligence_armorMultiplierRating", new NameModifier() { isSuffix=false, text="Shrewd" } },
        { "armorMultiplierRating_intelligence", new NameModifier() { isSuffix=false, text="Shrewd" } },
        { "intelligence_physicalResistRating", new NameModifier() { isSuffix=false, text="Vigorous" } },
        { "physicalResistRating_intelligence", new NameModifier() { isSuffix=false, text="Vigorous" } },
        { "intelligence_mentalResistRating", new NameModifier() { isSuffix=false, text="Clever" } },
        { "mentalResistRating_intelligence", new NameModifier() { isSuffix=false, text="Clever" } },
        { "intelligence_mpRating", new NameModifier() { isSuffix=false, text="Fabulous" } },
        { "mpRating_intelligence", new NameModifier() { isSuffix=false, text="Fabulous" } },
        { "intelligence_healingMultiplierRating", new NameModifier() { isSuffix=false, text="Benign" } },
        { "healingMultiplierRating_intelligence", new NameModifier() { isSuffix=false, text="Benign" } },
        { "intelligence_moveSpeedRating", new NameModifier() { isSuffix=false, text="Apt" } },
        { "moveSpeedRating_intelligence", new NameModifier() { isSuffix=false, text="Apt" } },
        { "intelligence_cooldownReductionRating", new NameModifier() { text="Wit" } },
        { "cooldownReductionRating_intelligence", new NameModifier() { text="Wit" } },
        { "intelligence_mpRegenRating", new NameModifier() { text="the Soothsayer" } },
        { "mpRegenRating_intelligence", new NameModifier() { text="the Soothsayer" } },
        { "intelligence_criticalHitChanceRating", new NameModifier() { isSuffix=false, text="Brainy" } },
        { "criticalHitChanceRating_intelligence", new NameModifier() { isSuffix=false, text="Brainy" } },
        { "intelligence_criticalDamageRating", new NameModifier() { text="Repartee" } },
        { "criticalDamageRating_intelligence", new NameModifier() { text="Repartee" } },
        { "intelligence_statusEffectDurationRating", new NameModifier() { isSuffix=false, text="Suave" } },
        { "statusEffectDurationRating_intelligence", new NameModifier() { isSuffix=false, text="Suave" } },
        { "intelligence_itemFindRating", new NameModifier() { isSuffix=false, text="Posh" } },
        { "itemFindRating_intelligence", new NameModifier() { isSuffix=false, text="Posh" } },
        { "intelligence_fireResistRating", new NameModifier() { isSuffix=false, text="Burning" } },
        { "fireResistRating_intelligence", new NameModifier() { isSuffix=false, text="Burning" } },
        { "intelligence_iceResistRating", new NameModifier() { text="the Icepick" } },
        { "iceResistRating_intelligence", new NameModifier() { text="the Icepick" } },
        { "intelligence_acidResistRating", new NameModifier() { text="Acrimony" } },
        { "acidResistRating_intelligence", new NameModifier() { text="Acrimony" } },
        { "intelligence_lightResistRating", new NameModifier() { isSuffix=false, text="Brilliant" } },
        { "lightResistRating_intelligence", new NameModifier() { isSuffix=false, text="Brilliant" } },
        { "intelligence_darkResistRating", new NameModifier() { isSuffix=false, text="Blacksnake" } },
        { "darkResistRating_intelligence", new NameModifier() { isSuffix=false, text="Blacksnake" } },
        { "intelligence_piercingResistRating", new NameModifier() { isSuffix=false, text="Piquant" } },
        { "piercingResistRating_intelligence", new NameModifier() { isSuffix=false, text="Piquant" } },
        { "intelligence_slashingResistRating", new NameModifier() { text="the Rapier" } },
        { "slashingResistRating_intelligence", new NameModifier() { text="the Rapier" } },
        { "intelligence_bashingResistRating", new NameModifier() { isSuffix=false, text="Rude" } },
        { "bashingResistRating_intelligence", new NameModifier() { isSuffix=false, text="Rude" } },

        { "wisdom_luck", new NameModifier() { text="the Natural" } },
        { "luck_wisdom", new NameModifier() { text="the Natural" } },
        { "wisdom_hpRating", new NameModifier() { isSuffix=false, text="Stoic" } },
        { "hpRating_wisdom", new NameModifier() { isSuffix=false, text="Stoic" } },
        { "wisdom_hpRegenRating", new NameModifier() { text="the Conservator" } },
        { "hpRegenRating_wisdom", new NameModifier() { text="the Conservator" } },
        { "wisdom_receivedHealingRating", new NameModifier() { text="Balm" } },
        { "receivedHealingRating_wisdom", new NameModifier() { text="Balm" } },
        { "wisdom_armorMultiplierRating", new NameModifier() { text="Athena" } },
        { "armorMultiplierRating_wisdom", new NameModifier() { text="Athena" } },
        { "wisdom_physicalResistRating", new NameModifier() { isSuffix=false, text="Zinc" } },
        { "physicalResistRating_wisdom", new NameModifier() { isSuffix=false, text="Zinc" } },
        { "wisdom_mentalResistRating", new NameModifier() { isSuffix=false, text="Stern" } },
        { "mentalResistRating_wisdom", new NameModifier() { isSuffix=false, text="Stern" } },
        { "wisdom_mpRating", new NameModifier() { isSuffix=false, text="Wizard" } },
        { "mpRating_wisdom", new NameModifier() { isSuffix=false, text="Wizard" } },
        { "wisdom_healingMultiplierRating", new NameModifier() { text="the Priest" } },
        { "healingMultiplierRating_wisdom", new NameModifier() { text="the Priest" } },
        { "wisdom_moveSpeedRating", new NameModifier() { text="the Aphorism" } },
        { "moveSpeedRating_wisdom", new NameModifier() { text="the Aphorism" } },
        { "wisdom_cooldownReductionRating", new NameModifier() { isSuffix=false, text="Sagacious" } },
        { "cooldownReductionRating_wisdom", new NameModifier() { isSuffix=false, text="Sagacious" } },
        { "wisdom_mpRegenRating", new NameModifier() { text="the Shaman" } },
        { "mpRegenRating_wisdom", new NameModifier() { text="the Shaman" } },
        { "wisdom_criticalHitChanceRating", new NameModifier() { text="Cunning" } },
        { "criticalHitChanceRating_wisdom", new NameModifier() { text="Cunning" } },
        { "wisdom_criticalDamageRating", new NameModifier() { text="the Axiom" } },
        { "criticalDamageRating_wisdom", new NameModifier() { text="the Axiom" } },
        { "wisdom_statusEffectDurationRating", new NameModifier() { isSuffix=false, text="Politic" } },
        { "statusEffectDurationRating_wisdom", new NameModifier() { isSuffix=false, text="Politic" } },
        { "wisdom_itemFindRating", new NameModifier() { text="the Favored" } },
        { "itemFindRating_wisdom", new NameModifier() { text="the Favored" } },
        { "wisdom_fireResistRating", new NameModifier() { text="the Meteor" } },
        { "fireResistRating_wisdom", new NameModifier() { text="the Meteor" } },
        { "wisdom_iceResistRating", new NameModifier() { text="the Blizzard" } },
        { "iceResistRating_wisdom", new NameModifier() { text="the Blizzard" } },
        { "wisdom_acidResistRating", new NameModifier() { isSuffix=false, text="Sumac" } },
        { "acidResistRating_wisdom", new NameModifier() { isSuffix=false, text="Sumac" } },
        { "wisdom_lightResistRating", new NameModifier() { isSuffix=false, text="Luminous" } },
        { "lightResistRating_wisdom", new NameModifier() { isSuffix=false, text="Luminous" } },
        { "wisdom_darkResistRating", new NameModifier() { isSuffix=false, text="Gray" } },
        { "darkResistRating_wisdom", new NameModifier() { isSuffix=false, text="Gray" } },
        { "wisdom_piercingResistRating", new NameModifier() { text="the Perspicacious" } },
        { "piercingResistRating_wisdom", new NameModifier() { text="the Perspicacious" } },
        { "wisdom_slashingResistRating", new NameModifier() { isSuffix=false, text="Keen" } },
        { "slashingResistRating_wisdom", new NameModifier() { isSuffix=false, text="Keen" } },
        { "wisdom_bashingResistRating", new NameModifier() { text="the Mace" } },
        { "bashingResistRating_wisdom", new NameModifier() { text="the Mace" } },

        { "luck_hpRating", new NameModifier() { isSuffix=false, text="Auspicious" } },
        { "hpRating_luck", new NameModifier() { isSuffix=false, text="Auspicious" } },
        { "luck_hpRegenRating", new NameModifier() { text="the Atavistic" } },
        { "hpRegenRating_luck", new NameModifier() { text="the Atavistic" } },
        { "luck_receivedHealingRating", new NameModifier() { text="the Blessed" } },
        { "receivedHealingRating_luck", new NameModifier() { text="the Blessed" } },
        { "luck_armorMultiplierRating", new NameModifier() { isSuffix=false, text="Carefree" } },
        { "armorMultiplierRating_luck", new NameModifier() { isSuffix=false, text="Carefree" } },
        { "luck_physicalResistRating", new NameModifier() { isSuffix=false, text="Hardy" } },
        { "physicalResistRating_luck", new NameModifier() { isSuffix=false, text="Hardy" } },
        { "luck_mentalResistRating", new NameModifier() { text="the Oak" } },
        { "mentalResistRating_luck", new NameModifier() { text="the Oak" } },
        { "luck_mpRating", new NameModifier() { text="Mojo" } },
        { "mpRating_luck", new NameModifier() { text="Mojo" } },
        { "luck_healingMultiplierRating", new NameModifier() { text="the Insouciant" } },
        { "healingMultiplierRating_luck", new NameModifier() { text="the Insouciant" } },
        { "luck_moveSpeedRating", new NameModifier() { isSuffix=false, text="Slapdash" } },
        { "moveSpeedRating_luck", new NameModifier() { isSuffix=false, text="Slapdash" } },
        { "luck_cooldownReductionRating", new NameModifier() { text="the Ace" } },
        { "cooldownReductionRating_luck", new NameModifier() { text="the Ace" } },
        { "luck_mpRegenRating", new NameModifier() { text="the Moon" } },
        { "mpRegenRating_luck", new NameModifier() { text="the Moon" } },
        { "luck_criticalHitChanceRating", new NameModifier() { text="the Jinx" } },
        { "criticalHitChanceRating_luck", new NameModifier() { text="the Jinx" } },
        { "luck_criticalDamageRating", new NameModifier() { text="the Devil" } },
        { "criticalDamageRating_luck", new NameModifier() { text="the Devil" } },
        { "luck_statusEffectDurationRating", new NameModifier() { isSuffix=false, text="Fortuitous" } },
        { "statusEffectDurationRating_luck", new NameModifier() { isSuffix=false, text="Fortuitous" } },
        { "luck_itemFindRating", new NameModifier() { text="the Favored" } },
        { "itemFindRating_luck", new NameModifier() { text="the Favored" } },
        { "luck_fireResistRating", new NameModifier() { text="the Hot Streak" } },
        { "fireResistRating_luck", new NameModifier() { text="the Hot Streak" } },
        { "luck_iceResistRating", new NameModifier() { isSuffix=false, text="Cool" } },
        { "iceResistRating_luck", new NameModifier() { isSuffix=false, text="Cool" } },
        { "luck_acidResistRating", new NameModifier() { isSuffix=false, text="Sour" } },
        { "acidResistRating_luck", new NameModifier() { isSuffix=false, text="Sour" } },
        { "luck_lightResistRating", new NameModifier() { isSuffix=false, text="Blithe" } },
        { "lightResistRating_luck", new NameModifier() { isSuffix=false, text="Blithe" } },
        { "luck_darkResistRating", new NameModifier() { isSuffix=false, text="Faustian" } },
        { "darkResistRating_luck", new NameModifier() { isSuffix=false, text="Faustian" } },
        { "luck_piercingResistRating", new NameModifier() { isSuffix=false, text="Mithril" } },
        { "piercingResistRating_luck", new NameModifier() { isSuffix=false, text="Mithril" } },
        { "luck_slashingResistRating", new NameModifier() { isSuffix=false, text="Acute" } },
        { "slashingResistRating_luck", new NameModifier() { isSuffix=false, text="Acute" } },
        { "luck_bashingResistRating", new NameModifier() { text="Adversity" } },
        { "bashingResistRating_luck", new NameModifier() { text="Adversity" } },

        { "hpRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_hpRating", new NameModifier() { } },
        { "hpRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_hpRating", new NameModifier() { } },
        { "hpRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_hpRating", new NameModifier() { } },
        { "hpRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_hpRating", new NameModifier() { } },
        { "hpRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_hpRating", new NameModifier() { } },
        { "hpRating_mpRating", new NameModifier() { } },
        { "mpRating_hpRating", new NameModifier() { } },
        { "hpRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_hpRating", new NameModifier() { } },
        { "hpRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_hpRating", new NameModifier() { } },
        { "hpRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_hpRating", new NameModifier() { } },
        { "hpRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_hpRating", new NameModifier() { } },
        { "hpRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_hpRating", new NameModifier() { } },
        { "hpRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_hpRating", new NameModifier() { } },
        { "hpRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_hpRating", new NameModifier() { } },
        { "hpRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_hpRating", new NameModifier() { } },
        { "hpRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_hpRating", new NameModifier() { } },
        { "hpRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_hpRating", new NameModifier() { } },
        { "hpRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_hpRating", new NameModifier() { } },
        { "hpRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_hpRating", new NameModifier() { } },
        { "hpRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_hpRating", new NameModifier() { } },
        { "hpRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_hpRating", new NameModifier() { } },
        { "hpRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_hpRating", new NameModifier() { } },
        { "hpRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_hpRating", new NameModifier() { } },

        { "hpRegenRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_mpRating", new NameModifier() { } },
        { "mpRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_hpRegenRating", new NameModifier() { } },
        { "hpRegenRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_hpRegenRating", new NameModifier() { } },

        { "receivedHealingRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_mpRating", new NameModifier() { } },
        { "mpRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_receivedHealingRating", new NameModifier() { } },
        { "receivedHealingRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_receivedHealingRating", new NameModifier() { } },

        { "armorMultiplierRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_mpRating", new NameModifier() { } },
        { "mpRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_armorMultiplierRating", new NameModifier() { } },
        { "armorMultiplierRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_armorMultiplierRating", new NameModifier() { } },

        { "physicalResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_mpRating", new NameModifier() { } },
        { "mpRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_physicalResistRating", new NameModifier() { } },
        { "physicalResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_physicalResistRating", new NameModifier() { } },

        { "mentalResistRating_mpRating", new NameModifier() { } },
        { "mpRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_mentalResistRating", new NameModifier() { } },
        { "mentalResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_mentalResistRating", new NameModifier() { } },

        { "mpRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_mpRating", new NameModifier() { } },
        { "mpRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_mpRating", new NameModifier() { } },
        { "mpRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_mpRating", new NameModifier() { } },
        { "mpRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_mpRating", new NameModifier() { } },
        { "mpRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_mpRating", new NameModifier() { } },
        { "mpRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_mpRating", new NameModifier() { } },
        { "mpRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_mpRating", new NameModifier() { } },
        { "mpRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_mpRating", new NameModifier() { } },
        { "mpRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_mpRating", new NameModifier() { } },
        { "mpRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_mpRating", new NameModifier() { } },
        { "mpRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_mpRating", new NameModifier() { } },
        { "mpRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_mpRating", new NameModifier() { } },
        { "mpRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_mpRating", new NameModifier() { } },
        { "mpRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_mpRating", new NameModifier() { } },
        { "mpRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_mpRating", new NameModifier() { } },
        { "mpRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_mpRating", new NameModifier() { } },

        { "healingMultiplierRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_healingMultiplierRating", new NameModifier() { } },
        { "healingMultiplierRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_healingMultiplierRating", new NameModifier() { } },

        { "moveSpeedRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_moveSpeedRating", new NameModifier() { } },
        { "moveSpeedRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_moveSpeedRating", new NameModifier() { } },

        { "cooldownReductionRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_cooldownReductionRating", new NameModifier() { } },
        { "cooldownReductionRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_cooldownReductionRating", new NameModifier() { } },

        { "mpRegenRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_mpRegenRating", new NameModifier() { } },
        { "mpRegenRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_mpRegenRating", new NameModifier() { } },

        { "criticalHitChanceRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_criticalHitChanceRating", new NameModifier() { } },
        { "criticalHitChanceRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_criticalHitChanceRating", new NameModifier() { } },

        { "criticalDamageRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_criticalDamageRating", new NameModifier() { } },
        { "criticalDamageRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_criticalDamageRating", new NameModifier() { } },

        { "statusEffectDurationRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_statusEffectDurationRating", new NameModifier() { } },
        { "statusEffectDurationRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_statusEffectDurationRating", new NameModifier() { } },

        { "itemFindRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_itemFindRating", new NameModifier() { } },
        { "itemFindRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_itemFindRating", new NameModifier() { } },

        { "fireResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_fireResistRating", new NameModifier() { } },
        { "fireResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_fireResistRating", new NameModifier() { } },

        { "iceResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_iceResistRating", new NameModifier() { } },
        { "iceResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_iceResistRating", new NameModifier() { } },

        { "acidResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_acidResistRating", new NameModifier() { } },
        { "acidResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_acidResistRating", new NameModifier() { } },

        { "lightResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_lightResistRating", new NameModifier() { } },
        { "lightResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_lightResistRating", new NameModifier() { } },

        { "darkResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_darkResistRating", new NameModifier() { } },
        { "darkResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_darkResistRating", new NameModifier() { } },

        { "piercingResistRating_slashingResistRating", new NameModifier() { } },
        { "slashingResistRating_piercingResistRating", new NameModifier() { } },
        { "piercingResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_piercingResistRating", new NameModifier() { } },

        { "slashingResistRating_bashingResistRating", new NameModifier() { } },
        { "bashingResistRating_slashingResistRating", new NameModifier() { } },

        { "strength_", new NameModifier() { isSuffix=false, text="Strong" } },
        { "dexterity_", new NameModifier() { isSuffix=false, text="Dexterous" } },
        { "constitution_", new NameModifier() { text="Stamina" } },
        { "intelligence_", new NameModifier() { text="Genius" } },
        { "wisdom_", new NameModifier() { text="Sagacity" } },
        { "luck_", new NameModifier() { text="Fortune" } },
        { "hpRating_", new NameModifier() { text="Tenacity" } },
        { "hpRegenRating_", new NameModifier() { text="Recovery" } },
        { "receivedHealingRating_", new NameModifier() { isSuffix=false, text="Curative" } },
        { "armorMultiplierRating_", new NameModifier() { text="Reinforcement" } },
        { "physicalResistRating_", new NameModifier() { isSuffix=false, text="Inuring" } },
        { "mentalResistRating_", new NameModifier() { isSuffix=false, text="Bracing" } },
        { "mpRating_", new NameModifier() { isSuffix=false, text="Sorcerous" } },
        { "healingMultiplierRating_", new NameModifier() { isSuffix=false, text="Palliative" } },
        { "moveSpeedRating_", new NameModifier() { text="Swiftness" } },
        { "cooldownReductionRating_", new NameModifier() { text="the Quick-Witted" } },
        { "mpRegenRating_", new NameModifier() { text="Magic" } },
        { "criticalHitChanceRating_", new NameModifier() { text="the Knife" } },
        { "criticalDamageRating_", new NameModifier() { isSuffix=false, text="Intense" } },
        { "statusEffectDurationRating_", new NameModifier() { isSuffix=false, text="Fortunate" } },
        { "itemFindRating_", new NameModifier() { text="Advantage" } },
        { "fireResistRating_", new NameModifier() { isSuffix=false, text="Flaming" } },
        { "iceResistRating_", new NameModifier() { isSuffix=false, text="Icy" } },
        { "acidResistRating_", new NameModifier() { isSuffix=false, text="Acidic" } },
        { "lightResistRating_", new NameModifier() { isSuffix=false, text="Bright" } },
        { "darkResistRating_", new NameModifier() { isSuffix=false, text="Dark" } },
        { "piercingResistRating_", new NameModifier() { isSuffix=false, text="Piercing" } },
        { "slashingResistRating_", new NameModifier() { isSuffix=false, text="Slashing" } },
        { "bashingResistRating_", new NameModifier() { isSuffix=false, text="Bashing" } },
    };

    private readonly static List<Dictionary<string, string>> baseNames = new List<Dictionary<string, string>> {
        new Dictionary<string, string>() {
            { "Sword", "Rusty Sword" },
            { "Wand", "Chipped Wand" },
            { "Bow", "Worn Bow" },
            { "Armor", "Cloth Armor" },
            { "Necklace", "Frayed Loop" },
            { "Belt", "Weathered Belt" },
            { "Bracelet", "Tacky Bangle" },
            { "Cloak", "Tattered Cloak" },
            { "Earring", "Tacky Earring" },
            { "Hat", "Weathered Hat" },
            { "Shoes", "Frayed Mittens" }
        },
        new Dictionary<string, string>() {
            { "Sword", "Sword" },
            { "Wand", "Wand" },
            { "Bow", "Bow" },
            { "Armor", "Leather Armor" },
            { "Necklace", "Necklace" },
            { "Belt", "Belt" },
            { "Bracelet", "Bracelet" },
            { "Cloak", "Cloak" },
            { "Earring", "Earring" },
            { "Hat", "Hat" },
            { "Shoes", "Shoes" }
        },
        new Dictionary<string, string>() {
            { "Sword", "Longsword" },
            { "Wand", "Polished Wand" },
            { "Bow", "Longbow" },
            { "Armor", "Chainmail" },
            { "Necklace", "Metal Necklace" },
            { "Belt", "Leather Belt" },
            { "Bracelet", "Shiny Bracelet" },
            { "Cloak", "Silk Cloak" },
            { "Earring", "Silver Earring" },
            { "Hat", "Bolero" },
            { "Shoes", "Boots" }
        },
        new Dictionary<string, string>() {
            { "Sword", "Mithril Sword" },
            { "Wand", "Liveoak Wand" },
            { "Bow", "Enchanted Longbow" },
            { "Armor", "Mithril Armor" },
            { "Necklace", "Mithril Necklace" },
            { "Belt", "Mithril Belt" },
            { "Bracelet", "Mithril Bracelet" },
            { "Cloak", "Skysilk Cloak" },
            { "Earring", "Mithril Earring" },
            { "Hat", "Fez" },
            { "Shoes", "Enchanted Boots" }
        },
        new Dictionary<string, string>() {
            { "Sword", "Gladius" },
            { "Wand", "Wizard's Wand" },
            { "Bow", "Masterful Bow" },
            { "Armor", "Plate Mail" },
            { "Necklace", "Gold Necklace" },
            { "Belt", "Gold Belt" },
            { "Bracelet", "Gold Bracelet" },
            { "Cloak", "Royal Cloak" },
            { "Earring", "Diamond Earring" },
            { "Hat", "Skullcap" },
            { "Shoes", "Mithril Greaves" }
        },
        new Dictionary<string, string>() {
            { "Sword", "Ancient Sword" },
            { "Wand", "Ancient Wand" },
            { "Bow", "Ancient Bow" },
            { "Armor", "Ancient Plate" },
            { "Necklace", "Ancestral Necklace" },
            { "Belt", "Ritual Belt" },
            { "Bracelet", "Ancient Bracelet" },
            { "Cloak", "Imperial Cloak" },
            { "Earring", "Godstear Earring" },
            { "Hat", "Turban" },
            { "Shoes", "Ancient Greaves" }
        },
        new Dictionary<string, string>() {
            { "Sword", "Godsword" },
            { "Wand", "Heavenly Wand" },
            { "Bow", "Godsbow" },
            { "Armor", "Diamond Plate" },
            { "Necklace", "Godstear Necklace" },
            { "Belt", "Diamond Belt" },
            { "Bracelet", "Glowing Bracelet" },
            { "Cloak", "Whispersilk Cloak" },
            { "Earring", "Diadem Earring" },
            { "Hat", "Many-Colored Hat" },
            { "Shoes", "Splendid Shoes" }
        },
        new Dictionary<string, string>() {
            { "Sword", "Reality Cleaver" },
            { "Wand", "Creator's Wand" },
            { "Bow", "Skypiercer" },
            { "Armor", "Metalskin Armor" },
            { "Necklace", "Star Diadem Necklace" },
            { "Belt", "Godly Cinch" },
            { "Bracelet", "Resplendent Bangle" },
            { "Cloak", "Prismatic Cloak" },
            { "Earring", "Star Diadem Earring" },
            { "Hat", "Godhelm" },
            { "Shoes", "Gaia Boots" }
        }
    };

    public static void NameEquipment(Equipment item) {
        if (item is MeleeWeapon) item.name = "Sword";
        else if (item is RangedWeapon && ((RangedWeapon)item).usesInt) item.name = "Wand";
        else if (item is RangedWeapon) item.name = "Bow";
        else if (item is Armor) item.name = "Armor";
        else if (item is Necklace) item.name = "Necklace";
        else if (item is Belt) item.name = "Belt";
        else if (item is Bracelet) item.name = "Bracelet";
        else if (item is Cloak) item.name = "Cloak";
        else if (item is Earring) item.name = "Earring";
        else if (item is Hat) item.name = "Hat";
        else if (item is Shoes) item.name = "Shoes";
        ModifyName(item);
    }

    private static void ModifyName(Equipment item) {
        var stat = item.GetHighestStat();
        var stat2 = item.GetSecondHighestStat();
        var statMashup = stat + "_" + stat2;
        item.name = baseNames[item.quality][item.name];
        if (statMashup!="_") item.name = modifiers[statMashup].GetModifier(item.name);
    }

    public static string GetHpAndMp(Armor item) {
        var character = GetCharacter();
        return "<b>HP</b>: " + Mathf.Floor(CharacterAttribute.attributes["bonusHp"].instances[character].TotalValue).ToString() + " <b>MP</b>: " + Mathf.Floor(CharacterAttribute.attributes["bonusHp"].instances[character].TotalValue).ToString();
    }

    public static string GetAttackPower(Weapon item) {
        var character = GetCharacter();
        if (item is MeleeWeapon) return "<b>Attack Power</b>: " + Mathf.Floor(item.attackPower * CharacterAttribute.attributes["strength"].instances[character].TotalValue).ToString();
        else if (item is RangedWeapon && ((RangedWeapon)item).usesInt) return "<b>Attack Power</b>: " + Mathf.Floor(item.attackPower * CharacterAttribute.attributes["intelligence"].instances[character].TotalValue).ToString();
        else if (item is RangedWeapon) return "<b>Attack Power</b>: " + Mathf.Floor(item.attackPower * CharacterAttribute.attributes["dexterity"].instances[character].TotalValue).ToString();
        return "";
    }

    public static string GetAttackPowerFromStat(float attackPower, string subtype) {
        if (subtype == "") return "Unknown";
        var character = GetCharacter();
        if (subtype == "strength") return "<b>Attack Power</b>: " + Mathf.Floor(attackPower * CharacterAttribute.attributes["strength"].instances[character].TotalValue).ToString();
        else if (subtype == "intelligence") return "<b>Attack Power</b>: " + Mathf.Floor(attackPower * CharacterAttribute.attributes["intelligence"].instances[character].TotalValue).ToString();
        else if (subtype == "dexterity") return "<b>Attack Power</b>: " + Mathf.Floor(attackPower * CharacterAttribute.attributes["dexterity"].instances[character].TotalValue).ToString();
        return "";
    }

    public static int GetAttackPowerNumberFromItem(Item item) {
        if (!(item is Weapon weapon)) return 0;
        var character = GetCharacter();
        if (item is MeleeWeapon) return Mathf.FloorToInt(weapon.attackPower * CharacterAttribute.attributes["strength"].instances[character].TotalValue);
        else if (item is RangedWeapon && ((RangedWeapon)weapon).usesInt) return Mathf.FloorToInt(weapon.attackPower * CharacterAttribute.attributes["intelligence"].instances[character].TotalValue);
        else return Mathf.FloorToInt(weapon.attackPower * CharacterAttribute.attributes["dexterity"].instances[character].TotalValue);
        //if (subtype == "") return 0;
        //var character = GetCharacter();
        //if (subtype == "strength") return Mathf.FloorToInt(attackPower * CharacterAttribute.attributes["strength"].instances[character].TotalValue);
        //else if (subtype == "intelligence") return Mathf.FloorToInt(attackPower * CharacterAttribute.attributes["intelligence"].instances[character].TotalValue);
        //else if (subtype == "dexterity") return Mathf.FloorToInt(attackPower * CharacterAttribute.attributes["dexterity"].instances[character].TotalValue);
        //return 0;
    }

    public static int GetAttackPowerNumber(Weapon item) {
        var character = GetCharacter();
        if (character == null) return 0;
        if (item is MeleeWeapon) return (int)Mathf.Floor(item.attackPower * CharacterAttribute.attributes["strength"].instances[character].TotalValue);
        else if (item is RangedWeapon && ((RangedWeapon)item).usesInt) return (int)Mathf.Floor(item.attackPower * CharacterAttribute.attributes["intelligence"].instances[character].TotalValue);
        else if (item is RangedWeapon) return (int)Mathf.Floor(item.attackPower * CharacterAttribute.attributes["dexterity"].instances[character].TotalValue);
        return 0;
    }

    private static Character GetCharacter() {
        if (PlayerCharacter.localPlayer == null) return null;
        return PlayerCharacter.localPlayer.GetComponent<Character>();
    }
}

public class NameModifier {
    public bool isSuffix = true;
    public string text = "";

    public string GetModifier(string baseName) {
        if (isSuffix) return baseName + " of " + text; 
        else return text + " " + baseName;
    }
}