// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: login.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class Login
{
  static readonly string __ServiceName = "Login";

  static readonly grpc::Marshaller<global::UserTokenRequest> __Marshaller_UserTokenRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::UserTokenRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::UserToken> __Marshaller_UserToken = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::UserToken.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::LogoutResult> __Marshaller_LogoutResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::LogoutResult.Parser.ParseFrom);

  static readonly grpc::Method<global::UserTokenRequest, global::UserToken> __Method_GetUserToken = new grpc::Method<global::UserTokenRequest, global::UserToken>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetUserToken",
      __Marshaller_UserTokenRequest,
      __Marshaller_UserToken);

  static readonly grpc::Method<global::UserToken, global::LogoutResult> __Method_Logout = new grpc::Method<global::UserToken, global::LogoutResult>(
      grpc::MethodType.Unary,
      __ServiceName,
      "Logout",
      __Marshaller_UserToken,
      __Marshaller_LogoutResult);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::LoginReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of Login</summary>
  public abstract partial class LoginBase
  {
    public virtual global::System.Threading.Tasks.Task<global::UserToken> GetUserToken(global::UserTokenRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::LogoutResult> Logout(global::UserToken request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for Login</summary>
  public partial class LoginClient : grpc::ClientBase<LoginClient>
  {
    /// <summary>Creates a new client for Login</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public LoginClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for Login that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public LoginClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected LoginClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected LoginClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::UserToken GetUserToken(global::UserTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetUserToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::UserToken GetUserToken(global::UserTokenRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetUserToken, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::UserToken> GetUserTokenAsync(global::UserTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetUserTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::UserToken> GetUserTokenAsync(global::UserTokenRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetUserToken, null, options, request);
    }
    public virtual global::LogoutResult Logout(global::UserToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Logout(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::LogoutResult Logout(global::UserToken request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_Logout, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::LogoutResult> LogoutAsync(global::UserToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return LogoutAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::LogoutResult> LogoutAsync(global::UserToken request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_Logout, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override LoginClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new LoginClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(LoginBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_GetUserToken, serviceImpl.GetUserToken)
        .AddMethod(__Method_Logout, serviceImpl.Logout).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, LoginBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_GetUserToken, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UserTokenRequest, global::UserToken>(serviceImpl.GetUserToken));
    serviceBinder.AddMethod(__Method_Logout, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UserToken, global::LogoutResult>(serviceImpl.Logout));
  }

}
#endregion
