// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test_server.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class Greeter
{
  static readonly string __ServiceName = "Greeter";

  static readonly grpc::Marshaller<global::TextMessage> __Marshaller_TextMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TextMessage.Parser.ParseFrom);

  static readonly grpc::Method<global::TextMessage, global::TextMessage> __Method_SayHello = new grpc::Method<global::TextMessage, global::TextMessage>(
      grpc::MethodType.Unary,
      __ServiceName,
      "SayHello",
      __Marshaller_TextMessage,
      __Marshaller_TextMessage);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::TestServerReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of Greeter</summary>
  public abstract partial class GreeterBase
  {
    public virtual global::System.Threading.Tasks.Task<global::TextMessage> SayHello(global::TextMessage request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for Greeter</summary>
  public partial class GreeterClient : grpc::ClientBase<GreeterClient>
  {
    /// <summary>Creates a new client for Greeter</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public GreeterClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for Greeter that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public GreeterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected GreeterClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected GreeterClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::TextMessage SayHello(global::TextMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::TextMessage SayHello(global::TextMessage request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::TextMessage> SayHelloAsync(global::TextMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::TextMessage> SayHelloAsync(global::TextMessage request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override GreeterClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new GreeterClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(GreeterBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, GreeterBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TextMessage, global::TextMessage>(serviceImpl.SayHello));
  }

}
#endregion
